Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

    config.vm.define "web01" do |web01|
        web01.vm.box = "spox/ubuntu-arm"
        web01.vm.hostname = "web01"
        web01.vm.network "private_network", ip: "192.168.56.40"
        web01.vm.network "public_network"

        web01.vm.provider "vmware_desktop" do |vb|
            vb.memory = "1024"
            vb.gui = false
            vb.vmx["ethernet0.virtualdev"] = "vmxnet3"
            vb.vmx["ethernet1.virtualdev"] = "vmxnet3"
            vb.vmx["ethernet2.virtualdev"] = "vmxnet3"
            vb.vmx["ethernet0.pciSlotNumber"] = "160"
            vb.vmx["ethernet1.pciSlotNumber"] = "192"
            vb.vmx["ethernet2.pciSlotNumber"] = "256"
        end
    end

    config.vm.define "web02" do |web02|
        web02.vm.box = "spox/ubuntu-arm"
        web02.vm.hostname = "web02"
        web02.vm.network "private_network", ip: "192.168.56.42"
        web02.vm.network "public_network"

        web02.vm.provider "vmware_desktop" do |vb|
            vb.memory = "1024"
            vb.gui = false
            vb.vmx["ethernet0.virtualdev"] = "vmxnet3"
            vb.vmx["ethernet1.virtualdev"] = "vmxnet3"
            vb.vmx["ethernet2.virtualdev"] = "vmxnet3"
            vb.vmx["ethernet0.pciSlotNumber"] = "160"
            vb.vmx["ethernet1.pciSlotNumber"] = "192"
            vb.vmx["ethernet2.pciSlotNumber"] = "256"
        end
    end


    config.vm.define "db01" do |db01|
        db01.vm.box = "shk/centos-stream-9-arm64"
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", ip: "192.168.56.46"
        db01.vm.network "public_network"

        db01.vm.provider "vmware_desktop" do |vb|
            vb.memory = "1024"
            vb.gui = false
            vb.vmx["ethernet0.virtualdev"] = "vmxnet3"
            vb.vmx["ethernet1.virtualdev"] = "vmxnet3"
            vb.vmx["ethernet2.virtualdev"] = "vmxnet3"
            vb.vmx["ethernet0.pciSlotNumber"] = "160"
            vb.vmx["ethernet1.pciSlotNumber"] = "192"
            vb.vmx["ethernet2.pciSlotNumber"] = "256"
        end

        db01.vm.provision "shell", inline: <<-SHELL
            yum install mariadb-server -y
            systemctl start mariadb
            systemctl enable mariadb
            hostname db01
        SHELL
    end

end
